### PR TITLE
2 post data

### LINKED ISSUE #2: Parse out post data
Assuming there is some arbitrary JSON in the body of the post request, might be nice to autoparse and assign it to a `data` key in the context variable.

``` go
data := map[string]interface{}
... read the body into bytes and unmarshal it to `data` ...
ctx["data"] = data
```

Then, pass the ctx forward.

We're making some assumptions about the format of the json payload not being a list. I'm comfortable with that. For complex payloads, leave it up to the controller to navigate.

### PR DESCRIPTION
**Pull request by johnpneumann**
resolves #2

### CODE REVIEW

**Comment by tristanwietsma** [comment]
Should we check for content-type in post header?

```
"Content-Type:application/json"
```

**Comment by johnpneumann** [comment]
It's more explicit so I'd say yes. The only reason I originally omitted it was because we were by default marshaling the data to Json which I perceived as it just being a requirement. Should I implement form handling as well for urlencoded and multipart? Or just urlencoded?

**Comment by tristanwietsma** [comment]
ignoring forms; form data can die with 1999.

**Comment by johnpneumann** [comment]
lgtm

**Pull request merged**
